### ISSUE TITLE
enum DiscreteThreshold

### ISSUE THREAD

**Issue by Hellikandra** [dstl/SAPIENT-Proto-Files#1]
By looking in `registration.proto` : the definition of `enum DiscreteThreshold` is present but never used in the `message Registration`.
If we look in other proto files, the other place where `enum DiscreteThreshold`  is `task.proto`.

Question : 
- `registration.proto` : where the enum need to be used ?
- => by comparison with `task.proto`, is the enum need to be add in `ClassFilterDefinition`, `SubClassFilterDefinition`,  `BehaviourFilterDefinition`
- => if not necessary is make sense to remove it from `registration.proto` ?

**Comment by VibroAxe** [comment]
@srcolley have you seen this and is it answered in the proposed V2?

**Comment by Hellikandra** [comment]
can be close. the v2 is now updated.
