### ISSUE TITLE
Error in BSI Flex 335 V2 task.proto file

### ISSUE THREAD

**Issue by SLCarter** [dstl/SAPIENT-Proto-Files#5]
The `enum Control` in `task.proto` has value 4 reserved with a comment that the default task has been removed, the enum then goes on to define `CONTROL_DEFAULT` as having a value of 4.  This results in errors when attempting to generate code from the proto file.

The BSI Flex 335 V2 document does not have an enum entry defined with a value of 4 so I believe the `CONTROL_DEFAULT` in the proto file should be deleted from the `enum Control`.

**Comment by Hellikandra** [comment]
Hi,
If we want to be compliant with the BSI Flex 335 v2,  the `CONTROL_DEFAULT = 4` can be commented/deleted

**Comment by SLCarter** [comment]
The `task.proto` file has been updated as have the V2 release files.
